# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
            ],
        ),
    ]
