# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
