# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171019_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(default=123, max_length=200, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
