# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171020_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(default='None', max_length=50, verbose_name='Color'),
        ),
    ]
