# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171020_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hero_image',
            field=models.ImageField(max_length=255, upload_to='pictures'),
        ),
    ]
