# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171020_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=255, verbose_name='Slug'),
        ),
    ]
